// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface RichtextStoryblok {
  type: string;
  content?: RichtextStoryblok[];
  marks?: RichtextStoryblok[];
  attrs?: unknown;
  text?: string;
  [k: string]: unknown;
}

export interface AssetStoryblok {
  alt: string | null;
  copyright?: string | null;
  fieldtype: "asset";
  id: number;
  filename: string | null;
  name: string;
  title: string | null;
  focus: string | null;
  meta_data?: {
    [k: string]: unknown;
  };
  source?: string | null;
  is_external_url?: boolean;
  is_private?: boolean;
  src?: string;
  updated_at?: string;
  width?: number | null;
  height?: number | null;
  aspect_ratio?: number | null;
  public_id?: string | null;
  content_type?: string;
  [k: string]: unknown;
}

export interface ArticleStoryblok {
  title: string;
  blurb: string;
  body: RichtextStoryblok;
  relatedArticles?: (ISbStoryData<ArticleStoryblok> | string)[];
  category: number | string;
  datePublished: string;
  dateLastModified: string;
  seo: SeoStoryblok[];
  thumbnail: AssetStoryblok;
  media: AssetStoryblok;
  component: "article";
  _uid: string;
  [k: string]: unknown;
}

export interface ArticleListingsStoryblok {
  title: string;
  subtitle: string;
  excludeCategories?: (number | string)[];
  showCategoryTag?: boolean;
  component: "articleListings";
  _uid: string;
  [k: string]: unknown;
}

export interface BenefitStoryblok {
  icon?: AssetStoryblok;
  title?: string;
  description?: string;
  component: "benefit";
  _uid: string;
  [k: string]: unknown;
}

export interface BenefitsStoryblok {
  title?: string;
  description?: string;
  ctas?: LinkStoryblok[];
  benefits: BenefitStoryblok[];
  component: "benefits";
  _uid: string;
  [k: string]: unknown;
}

export interface BentoGridStoryblok {
  title?: string;
  items: BentoGridItemStoryblok[];
  component: "bentoGrid";
  _uid: string;
  [k: string]: unknown;
}

export interface BentoGridItemStoryblok {
  title: string;
  description: string;
  asset: AssetStoryblok;
  component: "bentoGridItem";
  _uid: string;
  [k: string]: unknown;
}

export interface CentreHeroStoryblok {
  title: string;
  subtitle?: string;
  component: "centreHero";
  _uid: string;
  [k: string]: unknown;
}

export interface ContactUsStoryblok {
  title: string;
  subtitle?: RichtextStoryblok;
  component: "contactUs";
  _uid: string;
  [k: string]: unknown;
}

export interface CtaSectionStoryblok {
  image?: AssetStoryblok;
  title: string;
  description: string;
  cta?: LinkStoryblok[];
  component: "ctaSection";
  _uid: string;
  [k: string]: unknown;
}

export interface CustomerStoryStoryblok {
  clientName: string;
  clientLogo: AssetStoryblok;
  title: string;
  subtitle: string;
  body: RichtextStoryblok;
  relatedCustomerStories?: (ISbStoryData<CustomerStoryStoryblok> | string)[];
  stats?: StatStoryblok[];
  seo: SeoStoryblok[];
  media?: AssetStoryblok;
  thumbnail: AssetStoryblok;
  component: "customerStory";
  _uid: string;
  [k: string]: unknown;
}

export interface CustomerStoryListingsStoryblok {
  title: string;
  subtitle: string;
  component: "customerStoryListings";
  _uid: string;
  [k: string]: unknown;
}

export interface DemoStoryblok {
  title: string;
  subtitle: string;
  bannerText?: string;
  bannerStars?: string;
  showBanner?: boolean;
  calendarEmbed: string;
  thankYouTitle: string;
  component: "demo";
  _uid: string;
  [k: string]: unknown;
}

export interface FaqStoryblok {
  question: string;
  answer: RichtextStoryblok;
  component: "faq";
  _uid: string;
  [k: string]: unknown;
}

export interface FaqListStoryblok {
  title?: string;
  faqItems: (ISbStoryData<FaqStoryblok> | string)[];
  component: "faqList";
  _uid: string;
  [k: string]: unknown;
}

export interface FinePrintStoryblok {
  title: string;
  lastModifiedDate: string;
  body: RichtextStoryblok;
  seo: SeoStoryblok[];
  component: "finePrint";
  _uid: string;
  [k: string]: unknown;
}

export interface FiresideChatStoryblok {
  title: string;
  watchTime: string;
  embed: string;
  blurb: string;
  quote?: TestimonialStoryblok[];
  datePublished: string;
  dateLastModified: string;
  seo: SeoStoryblok[];
  thumbnail: AssetStoryblok;
  component: "firesideChat";
  _uid: string;
  [k: string]: unknown;
}

export interface FiresideChatsListingsStoryblok {
  title: string;
  subtitle: string;
  subscribeLinks?: IconLinkStoryblok[];
  subscribeLinksCaption?: string;
  component: "firesideChatsListings";
  _uid: string;
  [k: string]: unknown;
}

export interface FooterStoryblok {
  linkColumns?: LinkColumnStoryblok[];
  component: "footer";
  _uid: string;
  [k: string]: unknown;
}

export interface FullWidthBentoGridStoryblok {
  items: BentoGridItemStoryblok[];
  component: "fullWidthBentoGrid";
  _uid: string;
  [k: string]: unknown;
}

export type MultilinkStoryblok =
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      anchor?: string;
      rel?: string;
      title?: string;
      prep?: string;
      linktype: "story";
      story?: {
        name: string;
        created_at?: string;
        published_at?: string;
        id: number;
        uuid: string;
        content?: {
          [k: string]: unknown;
        };
        slug: string;
        full_slug: string;
        sort_by_date?: null | string;
        position?: number;
        tag_list?: string[];
        is_startpage?: boolean;
        parent_id?: null | number;
        meta_data?: null | {
          [k: string]: unknown;
        };
        group_id?: string;
        first_published_at?: string;
        release_id?: null | number;
        lang?: string;
        path?: null | string;
        alternates?: unknown[];
        default_full_slug?: null | string;
        translated_slugs?: null | unknown[];
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      linktype: "url";
      rel?: string;
      title?: string;
      [k: string]: unknown;
    }
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      email?: string;
      linktype: "email";
      [k: string]: unknown;
    }
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      linktype: "asset";
      [k: string]: unknown;
    };

export interface IconLinkStoryblok {
  icon: AssetStoryblok;
  link: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "iconLink";
  _uid: string;
  [k: string]: unknown;
}

export interface LeftRightFeatureStoryblok {
  title?: string;
  description?: string;
  cta?: LinkStoryblok[];
  component: "leftRightFeature";
  _uid: string;
  [k: string]: unknown;
}

export interface LeftRightFeaturesStoryblok {
  reverse?: boolean;
  title: string;
  description: string;
  features: LeftRightFeatureStoryblok[];
  media: AssetStoryblok;
  component: "leftRightFeatures";
  _uid: string;
  [k: string]: unknown;
}

export interface LeftRightHeroStoryblok {
  title: string;
  subtitle: string;
  ctas?: LinkStoryblok[];
  media: AssetStoryblok;
  style: "" | "light" | "dark";
  component: "leftRightHero";
  _uid: string;
  [k: string]: unknown;
}

export interface LeftRightImageStoryblok {
  reverse?: boolean;
  style: "dark" | "light";
  title: string;
  description: string;
  benefits?: LeftRightImageBenefitStoryblok[];
  media: AssetStoryblok;
  component: "leftRightImage";
  _uid: string;
  [k: string]: unknown;
}

export interface LeftRightImageBenefitStoryblok {
  icon: AssetStoryblok;
  text: string;
  component: "leftRightImageBenefit";
  _uid: string;
  [k: string]: unknown;
}

export interface LinkStoryblok {
  linkText: string;
  link: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  linkStyle?: "default" | "button";
  component: "link";
  _uid: string;
  [k: string]: unknown;
}

export interface LinkColumnStoryblok {
  links?: LinkStoryblok[];
  component: "linkColumn";
  _uid: string;
  [k: string]: unknown;
}

export interface LinkDropdownStoryblok {
  dropdownTitle?: string;
  links?: LinkStoryblok[];
  component: "linkDropdown";
  _uid: string;
  [k: string]: unknown;
}

export interface MainHeroStoryblok {
  showBanner?: boolean;
  bannerText?: string;
  bannerStars?: string;
  title: string;
  subtitle: string;
  ctas?: LinkStoryblok[];
  media: AssetStoryblok;
  component: "mainHero";
  _uid: string;
  [k: string]: unknown;
}

export interface NavigationStoryblok {
  logo?: AssetStoryblok;
  centreLinks?: (LinkDropdownStoryblok | LinkStoryblok)[];
  rightLinks?: LinkStoryblok[];
  component: "navigation";
  _uid: string;
  [k: string]: unknown;
}

export interface PageStoryblok {
  body?: (
    | BentoGridStoryblok
    | CtaSectionStoryblok
    | LeftRightImageStoryblok
    | MainHeroStoryblok
    | ScrollingFeaturesStoryblok
    | StatsStoryblok
    | TestimonialStoryblok
    | CustomerStoryListingsStoryblok
    | ArticleListingsStoryblok
    | FiresideChatsListingsStoryblok
    | ContactUsStoryblok
    | LeftRightHeroStoryblok
  )[];
  seo: SeoStoryblok[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface PartnersStoryblok {
  title: string;
  subtitle?: string;
  logos: IconLinkStoryblok[];
  component: "partners";
  _uid: string;
  [k: string]: unknown;
}

export interface PricingHeroStoryblok {
  monthlyPrice: string;
  annualPrice: string;
  planFeatures: PricingTableFeatureStoryblok[];
  perUnitText: string;
  planDescription?: string;
  planCta: LinkStoryblok[];
  enterprisePlanCta: LinkStoryblok[];
  enterpriseDescription?: string;
  enterpriseTitle?: string;
  enterpriseFeatures: PricingTableFeatureStoryblok[];
  standard?: unknown;
  enterprise?: unknown;
  title: string;
  subtitle: string;
  component: "pricingHero";
  _uid: string;
  [k: string]: unknown;
}

export interface PricingTableFeatureStoryblok {
  icon?: AssetStoryblok;
  text: string;
  component: "pricingTableFeature";
  _uid: string;
  [k: string]: unknown;
}

export interface RedirectStoryblok {
  path: string;
  destination: string;
  status?: "" | "301" | "302" | "303" | "307" | "308" | "300" | "304";
  component: "redirect";
  _uid: string;
  [k: string]: unknown;
}

export interface RedirectsListStoryblok {
  redirects?: RedirectStoryblok[];
  component: "redirectsList";
  _uid: string;
  [k: string]: unknown;
}

export interface RelatedContentStoryblok {
  title?: string;
  relatedContentItems: unknown[];
  component: "relatedContent";
  _uid: string;
  [k: string]: unknown;
}

export interface ScrollingFeatureStoryblok {
  title: string;
  description: string;
  media: AssetStoryblok;
  component: "scrollingFeature";
  _uid: string;
  [k: string]: unknown;
}

export interface ScrollingFeaturesStoryblok {
  title?: string;
  features: ScrollingFeatureStoryblok[];
  component: "scrollingFeatures";
  _uid: string;
  [k: string]: unknown;
}

export interface SeoStoryblok {
  title?: string;
  description?: string;
  openGraphTitle?: string;
  noIndex?: boolean;
  openGraphImage?: AssetStoryblok;
  component: "seo";
  _uid: string;
  [k: string]: unknown;
}

export interface SeoDefaultsStoryblok {
  title: string;
  description: string;
  openGraphImage?: AssetStoryblok;
  openGraphTitle?: string;
  openGraphDescription?: string;
  noIndex?: boolean;
  twitterHandle?: string;
  component: "seoDefaults";
  _uid: string;
  [k: string]: unknown;
}

export interface StatStoryblok {
  text: string;
  caption: string;
  component: "stat";
  _uid: string;
  [k: string]: unknown;
}

export interface StatsStoryblok {
  title?: string;
  subtitle?: string;
  stats: StatStoryblok[];
  component: "stats";
  _uid: string;
  [k: string]: unknown;
}

export interface TeamStoryblok {
  title?: string;
  team: TeamMemberStoryblok[];
  secondaryTitle?: string;
  description?: string;
  component: "team";
  _uid: string;
  [k: string]: unknown;
}

export interface TeamMemberStoryblok {
  headshot: AssetStoryblok;
  name: string;
  role: string;
  bio: string;
  email: string;
  component: "teamMember";
  _uid: string;
  [k: string]: unknown;
}

export interface TestimonialStoryblok {
  quote: string;
  author: string;
  authorRoleCompany: string;
  authorHeadshot?: AssetStoryblok;
  component: "testimonial";
  _uid: string;
  [k: string]: unknown;
}

export interface ValuesStoryblok {
  title?: string;
  subtitle?: string;
  valueItems: BenefitStoryblok[];
  component: "values";
  _uid: string;
  [k: string]: unknown;
}
